name: ci

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

env:
  ENVIRONMENT: ${{ github.event_name == 'pull_request' && github.base_ref || github.ref_name }}

jobs:
  ci:
    # 「PRがトリガーのとき」または「直接マージのとき」のみ実行する
    if: ${{ github.event_name != 'push' || startsWith(github.ref, 'refs/heads/') }}
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'pull_request' && github.base_ref || github.ref_name }}
    steps:
      - run: echo if merge ${{ github.event.pull_request.merged }}
      - run: echo ${{ env.ENVIRONMENT }}
      - run: sleep 10
      - run: echo vars ${{ vars.test }}
  cd:
    # 「直接マージのとき」はCDも実行する
    if: ${{ startsWith(github.ref, 'refs/heads/') }}
    needs: ci
    uses: ./.github/workflows/cd.yml
