name: ci

on:
  # pull_request:
  #   types:
  #     - opened
  #     - synchronize
  #     - reopened
  #   branches:
  #     - prd
  #     - dev
  push:

env:
  ENVIRONMENT: ${{ github.event_name == 'pull_request' && github.base_ref || github.ref_name }}

jobs:
  ci:
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'pull_request' && github.base_ref || github.ref_name }}
    env:
      TEST: ${{ vars.TEST }}
    steps:
      - run: echo if merge ${{ github.event.pull_request.merged }}
      - run: echo branch ${{ env.ENVIRONMENT }}
      - run: sleep 10
      - run: echo vars ${{ vars.test }}
      - run: echo env ${{ env.test }}
