name: ci

on:
  push:
    branches:
      - dev
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - !closed
    branches:
      - dev


jobs:
  ci:
    if: ${{ github.event.pull_request.merged == false }}
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'pull_request' && github.base_ref || github.ref_name }}
    steps:
      - run: echo event_name ${{ github.event_name }}
      - run: echo base_ref ${{ github.base_ref }}
      - run: echo ref ${{ github.ref }}
      - run: echo ref_name ${{ github.ref_name }}
      - run: echo vars ${{ vars.test }}
  cd:
    if: ${{ github.event.pull_request.merged == true || github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    needs: ci
    environment: ${{ github.event_name == 'pull_request' && github.base_ref || github.ref_name }}
    steps:
      - run: echo event_name ${{ github.event_name }}
      - run: echo base_ref ${{ env.ENVIRONMENT }}
      - run: echo vars ${{ vars.test }}
      - run: echo this is CD
