name: ci

on:
  push:
    branches:
      - dev
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - prd
      - dev

env:
  ENVIRONMENT: ${{ github.event_name == 'pull_request' && github.base_ref || github.ref_name }}

jobs:
  ci:
    if: ${{ github.event.pull_request.merged == false }}
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'pull_request' && github.base_ref || github.ref_name }}
    steps:
      - run: echo if merge ${{ github.event.pull_request.merged }}
      - run: echo ${{ env.ENVIRONMENT }}
      - run: sleep 10
      - run: echo vars ${{ vars.test }}
  cd:
    if: ${{ github.event.pull_request.merged == true || github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    needs: ci
    environment: ${{ github.event_name == 'pull_request' && github.base_ref || github.ref_name }}
    steps:
      - run: echo if merge ${{ github.event.pull_request.merged }}
      - run: echo ${{ env.ENVIRONMENT }}
      - run: sleep 20
      - run: echo vars ${{ vars.test }}
