name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
    paths:
      - 'frontend/**'

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'frontend/'

    steps:
      - uses: actions/checkout@v4
      - run: echo CI frontend
